on: 
  push:
    branches: [master]
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: true
      matrix:
        version:
          - '1.12'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - name: "Get assignment and user name"
        shell: bash -l {0}
        run: |
          echo "ASSIGNMENT=$(echo $GITHUB_REPOSITORY | cut -d/ -f2 | cut -d- -f1)" >> $GITHUB_ENV;
          echo "GITHUB_USER=$(echo $GITHUB_REPOSITORY | cut -d/ -f2 | cut -d- -f2-)" >> $GITHUB_ENV;
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Fetch Tests"
        shell: bash -l {0}
        run: |
          mkdir -p test
          cd test
          curl \
          --header 'Authorization: token ${{secrets.PGE383_SECRET_TOKEN}}' \
          --header 'Accept: application/vnd.github.v3.raw' \
          -O --location "https://api.github.com/repos/PGE383-HPC/${ASSIGNMENT}-solution/contents/test/runtests.jl"
      - name: "Fetch Environment"
        shell: bash -l {0}
        run: |
          curl \
          --header 'Authorization: token ${{secrets.PGE383_SECRET_TOKEN}}' \
          --header 'Accept: application/vnd.github.v3.raw' \
          -O --location "https://api.github.com/repos/PGE383-HPC/${ASSIGNMENT}-solution/contents/Project.toml" \
          -O --location "https://api.github.com/repos/PGE383-HPC/${ASSIGNMENT}-solution/contents/Manifest.toml"
      - name: "Checkout dotfiles repo"
        uses: actions/checkout@v3
        with:
          repository: ${{ env.GITHUB_USER }}/dotfiles
          path: dotfiles
      - name: "Setup dotfiles and create lla.txt"
        shell: bash -l {0}
        run: |
          ./dotfiles/install.sh
          source ~/.bash_profile
          alias lla > lla.txt
      - name: "Build and Test"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - name: "Reset profile" 
        shell: bash -l {0}
        run: |
          mv $HOME/.bash_profile_backup $HOME/.bash_profile 
          mv $HOME/.bashrc_backup $HOME/.bashrc
          source $HOME/.bash_profile
          source $HOME/.bashrc
